### ISSUE TITLE
[Setting] 프로젝트 세팅

### ISSUE THREAD

**Issue by binisnil** [Team-Wable/WABLE-iOS#1]
## 개요
> 프로젝트 기초를 세팅합니다

## TODO

- [x] 폴더링
- [x] 라이브러리 추가
- [x] 네트워크 기초세팅
- [x] Extension 추가
- [x] 디자인시스템 추가
    - [x] 폰트 추가
    - [x] 디자인시스템 폰트 생성
    - [x] 컬러 시스템 추가
    - [x] 컴포넌트 생성
    - [x] 아이콘, 이미지 추가
    - [x] 탭바 세팅
    - [x] 네비바 세팅

==== Github 관련 세팅====
- [ ] PR 템플릿 생성
- [ ] ISSUE 템플릿 생성
- [x] 프로젝트 파일 레포지토리에 연결
- [ ] Labels 생성
- [x] .gitignore 파일 생성
