### ISSUE TITLE
[Fix] 릴리즈 전 QA 사항 반영

### ISSUE THREAD

**Issue by boogios** [Team-Wable/WABLE-iOS#47]
## 👻 Issue

> QA 사항 해결해보겠습니다~!

## 📝 To-do

- [ ] 마이페이지 탭 영역 고정
- [ ] 상세보기 뷰 QA 사항 반영
- [x] 마이페이지 알림 설정 텍스트 변경
- [ ] 게시글 작성 스크롤 영역 확대
