### ISSUE TITLE
[fix] 소식, 알림 탭 오류 수정

### ISSUE THREAD

**Issue by JinUng41** [Team-Wable/WABLE-iOS#55]
## 👻 Issue

> 소식 및 알림 페이지에서 발생하는 오류를 수정합니다.

## 📝 To-do

- [x] 오늘 경기가 아님에도 오늘 경기라고 표시되는 경우 (소식 -> 정보)
- [x] 타 유저의 인기글 알림임에도, 본인의 인기글로 표시되는 경우
- [ ] 알림에서 프로필 사진을 누르면 해당 사용자 프로필로 이동할 있도록 한다.
