### ISSUE TITLE
[Fix] 소식 탭 QA 반영 및 기타 기능 수정

### ISSUE THREAD

**Issue by JinUng41** [Team-Wable/WABLE-iOS#77]
## 👻 Issue

> 소식 탭 QA 내용 반영합니다.

## 📝 To-do

- [x] 뉴스 제목이 길 때 짤리지 않는 현상 수정
- [x] 소식 탭 리프레시, 강제종료되는 현상 수정
- [x] 사진 상세보기 뷰 닫기 버튼 위치 수정
- [x] 매치 정보 세션 네트워크 통신
- [x] 매치 날짜 매핑 수정
