### ISSUE TITLE
[Fix] 홈, 상세보기 QA 반영

### ISSUE THREAD

**Issue by binisnil** [Team-Wable/WABLE-iOS#79]
## 👻 Issue

> 1.1.0 버전 출시를 위한 QA사항을 반영합니다

## 📝 To-do

- [x] 마이페이지 게시글 안보이는 이슈
- [x] 게시글 작성 플레이스홀더 최신화
- [ ] 로딩뷰 홈상세 -> 홈으로 가면 뜨지 않도록
- [x] 알림에서 대댓글 관련 화면으로 안넘어가는 현상
- [x] 홈 피드에서 댓글 아이콘 누르면 상세보기로 안넘어감
- [x] 피드 블라인드 처리된 게시글은 투명도 적용 안되어야 함
- [ ] 벤하기 기능 구현
