### ISSUE TITLE
[Fix] 소식 탭 오류 수정 및 배지 구현, 알림 탭 이동 로직 구현

### ISSUE THREAD

**Issue by JinUng41** [Team-Wable/WABLE-iOS#80]
## 👻 Issue

> 소식 탭 뉴스와 공지사항의 알림 배지를 구현합니다.
> 그 와 더불어 소식 탭에 존재하는 오류를 해결합니다.

## 📝 To-do

- [x] UserDefaults를 활용한 로컬 DB 저장 및 활용
- [x] 소식 탭 공지사항 셀 UI 수정 (제목이 길어질 때, 시간이 보이지 않는 문제)
- [x] 알림 탭 활동 페이지 이동 로직 구현 (프로필 터치 시)
